---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install node 12.X"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt -y upgrade
    sudo apt install -y nodejs

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
